{
 "title": "IPv4 packet stream analysis (Prometheus)",
 "description": "Analysis of a real-time IPv4 packet stream as exported by prometheus-net/tzsp_packetstream_exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(tzsp_observed_bytes_total, instance)"
   },
   {
    "name": "from",
    "label": "From",
    "query": "label_values(tzsp_observed_bytes_total{instance =~ \"$instances\"}, from)"
   },
   {
    "name": "to",
    "label": "To",
    "query": "label_values(tzsp_observed_bytes_total{instance =~ \"$instances\"}, to)"
   },
   { "name": "protocol", "label": "Protocols", "query": "tcp,udp,unknown" }
  ]
 },
 "panels": [
  {
   "title": "Throughput per destination address type and protocol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tzsp_observed_bytes_total{instance =~ \"$instances\", from =~ \"$from\", to =~ \"$to\", protocol =~ \"$protocol\"}[3m]) * 8) by (to_type, protocol)",
     "legendFormat": "{{to_type}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "Current throughput by source address",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(tzsp_observed_bytes_total{instance =~ \"$instances\", from =~ \"$from\", to =~ \"$to\", protocol =~ \"$protocol\"}[3m]) * 8) by (from)"
    }
   ]
  },
  {
   "title": "Current throughput by destination address",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(tzsp_observed_bytes_total{instance =~ \"$instances\", from =~ \"$from\", to =~ \"$to\", protocol =~ \"$protocol\"}[3m]) * 8) by (to)"
    }
   ]
  }
 ]
}